set(HEADER_FILES
	include/PCH.h
	include/logger.h
	include/Plugin.h
	include/Hooks.h
	include/Manager.h
	include/Str.h
	include/AVObjects.h
	include/TimeClass.h
	include/SaveLoadManager.h
	include/InventoryManager.h
	include/UI.h
	include/SKSEMenuFramework.h
	include/Model.h
	include/ModelSwapManager.h
	include/Singleton.h
)
