set(HEADER_FILES
	include/PCH.h
	include/logger.h
	include/Plugin.h
	include/Hooks.h
	include/Manager.h
	include/Str.h
	include/Wrapper.h
	include/TimeClass.h
	include/SaveLoadManager.h
	include/Serialization.h
)
