set(SOURCE_FILES
	src/Plugin.cpp
	src/Manager.cpp
	src/Persistence.cpp
	src/Hooks.cpp
	src/SaveLoadManager.cpp
	src/Serialization.cpp
	src/InventoryManager.cpp
	src/UI.cpp
	src/ModelSwapManager.cpp
)
